### ISSUE TITLE
Is Sys-CPU 0.52 OK? Sys-CPU 0.61 seems to have vanished

### ISSUE THREAD

**Issue by ilovezfs** [csmith-project/creduce#152]
http://search.cpan.org/CPAN/authors/id/M/MZ/MZSANFORD/Sys-CPU-0.61.tar.gz
now 404.

And the most recent version is suddenly 0.52 http://search.cpan.org/~mkoderer/Sys-CPU-0.52/CPU.pm

Is this acceptable? I'm not sure what the back story is here but the Homebrew formula has had 0.61 since inception.

**Comment by dtzWill** [comment]
That's strange re:disappearing from mirrors and only showing 0.52 as latest.

FWIW seems to still be here:  https://cpan.metacpan.org/authors/id/M/MZ/MZSANFORD/Sys-CPU-0.61.tar.gz
(which, among other things, is the URL Arch uses: https://aur.archlinux.org/packages/perl-sys-cpu/)

Can't comment on whether 0.52 is new enough, I think it's only used for setting default parallelism so it's not exactly a complex API tightly integrated with the codebase :)...

Try it and report back, maybe?

**Comment by dtzWill** [comment]
Few quick updates:

* As far as I can tell `Sys::CPU` is an **optional** dependency for creduce, which attempts to use platform-specific tools like `lscpu` (Linux) and `sysctl hw` (Darwin) before "falling back" to checking with Sys::CPU if available.  For `csmith` I believe Sys::CPU is required by `launchn.pl`.
* Using `Sys::CPU` 0.52 seems to work just fine in some quick testing.
* I've been building against 0.61 as well, but no version is specified in the code or documentation so hopefully the authors don't know of specific reasons latest version must be used... else they'd probably mention them! :)

**Comment by dtzWill** [comment]
* [GitHub repo for `Sys::CPU`](https://github.com/mzsanford/perl-sys-cpu)
* Looks like 0.61 fixes a few bugs, [commit history is brief if you'd like to inspect it](https://github.com/mzsanford/perl-sys-cpu/commits/master) -- most notable change seems to FreeBSD support.

I know little of perl ecosystem so I'm not sure how to follow up on that--it does seem strange that the `0.61` version (by MZSANFORD instead of MKODERER) has disappeared.
(Are these things tracked somewhere?)

**Comment by ilovezfs** [comment]
@eeide if I understand the 2.8.0 release has removed this dependency entirely, correct?

**Comment by eeide** [comment]
Yes, that is right.

On Linux and macOS, it was not used anyway.

Thank you for the reminder to close this issue!
