### ISSUE TITLE
Time to drop indent and astyle?

### ISSUE THREAD

**Issue by octoploid** [csmith-project/creduce#43]
clang_format has matured a lot. Are astyle and indent still necessary?

**Comment by regehr** [comment]
What do you think about this @eeide?

**Comment by eeide** [comment]
Hmm. It is hard for me to judge if clang-format is strictly "superior" for our purpose, especially for ill-formed inputs. (Ill-formed inputs can easily arise, say, if someone is minimizing for a compiler crash.) Frankly, I don't use any of these tools on a regular basis outside of C-Reduce, so I don't have a personal feel for them.

For C-Reduce applied to non-C/C++ code, `astyle` claims to support C# and C++/CLI, which `clang-format` does not. (C++/CLI: https://en.wikipedia.org/wiki/C%2B%2B/CLI ) But maybe this is not enough justification to keep `astyle`.

For me, I guess the question is about the cost of keeping them. Dropping them won't make C-Reduce noticeably faster (almost certainly). I don't find it difficult to install `astyle` and `indent`, but I get the impression that some others do (?). In principle I'm all for eliminating external dependencies that we don't need.

Did I come down firmly on the fence there?

I guess that without  a strong benefit/desire for getting rid of `astyle` and `indent`, I would probably keep them, on the unsubstantiated theory that they might be better sometimes.

**Comment by octoploid** [comment]
As a data point: I've been using clang-format exclusively on several GCC compile farm machines for the last year without running into any trouble.
For C and C++ astyle and indent are obsolete IMHO.

**Comment by regehr** [comment]
Shouldn't it be easy to just drop the astyle and indent passes when these programs aren't detected by configure? I'm happy to do my part of this if Eric does the autocrap.

**Comment by eeide** [comment]
I wonder it might be preferable for the pass to dynamically configure itself, based on the run-time availability of the tools.

Our Autoconf setup checks for all of the indenters, and if they are found, it remembers where it found them. For each tool that is not found, `configure` prints a warning, but it does not cause the configuration process to fail.

We currently fail at run time, if any one of the indenter tools cannot be found. (C-Reduce checks the remembered configure-time value and the PATH.) We could change this so that it fails only if *none* of the tools can be found, say, and then the pass runs with whatever tools happen to be present.

The result would be different than the proposed configure-time option that says "never invoke `indent`, even if it is is available." But I think I like the dynamic configuration option better.

What do you think, @regehr ?

(Purely dynamic configuration also means no Autoconf changes, hooray for me :smiley:.)

**Comment by eeide** [comment]
Heh—I just realized that this issue was opened in October *2014*.

So I guess that `astyle` and `indent` are potentially even *more* obsolete this year!

**Comment by regehr** [comment]
I like it. This can be handled locally in pass_indent. I'll make it happen.

**Comment by regehr** [comment]
Was just reading the README. There are a lot of dependencies we could eliminate if we felt like it. Not sure how important that is now that many distros include a C-Reduce.

**Comment by regehr** [comment]
Ok I have pushed changes to INSTALL and to pass_indent making indent and astyle optional. All seems to be working fine, but now our configure's scripts warnings are too dire, can we tone this way down Eric? Not high priority.

```
## ------------------------------------------------------------------------ ##
## WARNING: You cannot run C-Reduce until you install missing dependencies! ##
## ------------------------------------------------------------------------ ##
configure: WARNING: You must install Artistic Style before running C-Reduce
configure: WARNING: You must install GNU Indent before running C-Reduce
configure: WARNING: Read the INSTALL file for info about C-Reduce dependencies
```

**Comment by eeide** [comment]
Yes, I will tone down the warnings.

**Comment by eeide** [comment]
@regehr: Your commit leaves `clang-format` as a required run-time dependency. Is that intentional?

**Comment by regehr** [comment]
Yes, we have a hard dependency on LLVM so this won't hurt anything.

**Comment by eeide** [comment]
I agree that it is largely moot whether `clang-format` is required or optional. The lack of parallel treatment merely set off my "that's different" detector.

**Comment by eeide** [comment]
Warnings toned down in commit 9e210c4.

**Comment by regehr** [comment]
Perfect. Closing. Thanks Eric and Markus.
