### ISSUE TITLE
Implement "skip to next pass" key

### ISSUE THREAD

**Issue by octoploid** [csmith-project/creduce#74]
One feature that I miss often is the ability to skip to next pass by simply pressing a key (say 's').
Ctrl-c works in some circumstances, but is obviously timing depended and error prone.

**Comment by regehr** [comment]
Yeah this is a good idea. Maybe also a signal handler that has the same behavior since I most often run slow C-Reduces under nohup so they stay alive if my ssh dies.

Related: something I had on my TODO list was adding a command line option for aborting a pass if it runs for longer than a configurable amount of time. Perhaps both this and the skip key are useful.

**Comment by regehr** [comment]
FWIW it looks like the easy + right way to get this is to use this module:
http://search.cpan.org/~jstowe/TermReadKey-2.33/ReadKey.pm

**Comment by regehr** [comment]
Please try it out. Appears to work fine on OS X and Linux.

**Comment by eeide** [comment]
I have not looked at the patch, but I was wondering if it would be good to have some way to disable this, for when you really want C-Reduce to run in batch mode. E.g., because you're doing a long-running experiment, and you're watching it because you're curious, and you don't want a stray input to affect the outcome.

But maybe a "serious" batch run of C-Reduce wouldn't be connected to a terminal anyway.

Anyway, idle pondering.

**Comment by octoploid** [comment]
Thanks a lot for the quick implementation John!
Works like a charm.
