### ISSUE TITLE
Inconsistent 2.5.0 release tarball 

### ISSUE THREAD

**Issue by maxim-belkin** [csmith-project/creduce#94]
There is a difference between 2.5.0 tarball file that is provided here on github and the one on utah.edu website:
```
$ diff -rw creduce-github-2.5.0/ creduce-utah-2.5.0/
Only in creduce-github-2.5.0/: .gitattributes
Only in creduce-github-2.5.0/: .gitignore
Only in creduce-github-2.5.0/: .travis.yml
Only in creduce-github-2.5.0/: Dockerfile
Only in creduce-github-2.5.0/: bootstrap
Only in creduce-github-2.5.0/clang_delta: .gitignore
Only in creduce-github-2.5.0/clex: .gitignore
Only in creduce-utah-2.5.0/clex: clex.c
Only in creduce-utah-2.5.0/clex: strlex.c
Only in creduce-github-2.5.0/creduce: .gitignore
Only in creduce-github-2.5.0/delta: .gitignore
Only in creduce-utah-2.5.0/delta: topformflat.c
Only in creduce-github-2.5.0/scripts: travis_deps.sh
Only in creduce-github-2.5.0/tests: .gitignore
Only in creduce-github-2.5.0/unifdef: .gitignore
```

**Comment by eeide** [comment]
Hi! These differences are intentional.

The rest of this message explains the differences, but in short: the content of the two tarballs is "basically the same," and C-Reduce 2.5.0 should work the same regardless of which tarball you use.

My nutshell recommendation: If you want an "official release" of C-Reduce, or if you want to repackage C-Reduce (say, for some Linux distro), I'd suggest that you use the tarball found at utah.edu. On the other hand, if you want to track the current version of C-Reduce, or if you just want to get C-Reduce via git, then I'd suggest that you clone the repository found at GitHub.

*At utah.edu...*

The "release" tarballs at available at utah.edu are intended for people who want to use C-Reduce but who do not intend to contribute to its development. For this reason, the tarballs do not include files that are only of use to the developers of C-Reduce. This includes "control files" related to git and Travis-CI, and also the "bootstrap" file, which is specific to reconfiguring the Autoconf-based build system.

The release tarballs also include ".c" files that are generated by lex/flex. This means that users don't need to install lex/flex in order to compiler C-Reduce. (This is a historic practice, dating from a time when lex/flex were somewhat less portable than they are today.)

Another special thing about the release tarballs is that the "git-hash.sh" script is modified to contain the (short) hash of the git commit from which the release was made. (Normally, "git-hash.sh" tries to figure out the commit hash when the script is run; the modified version of the script in the release tarballs has the commit hash "baked in.")

*At Github...*

GitHub makes tarballs by simply tar'ing up the entire tree at a particular commit. As far as I know, this behavior cannot be changed. Thus, as you noted, the tarballs that one can download from GitHub is slightly different than the "release tarballs" that we make available at utah.edu.

I believe that GitHub offers this auto-tar'ing as a service to developers who don't want to make release tarballs on their own. I guess it's also a service to users, who maybe don't want to go hunting for release tarballs at other websites, or who for whatever reason need a "snapshot" of a repository without all the git metadata and history. (Maybe for a CI system?)

In general, I guess I would suggest not using the C-Reduce tarballs that are automatically produced by GitHub, unless you have a special use-case of some kind. There's nothing really "wrong" with them, I suppose, but they are sort of odd in the sense that they contain all the only-useful-to-developers goo without the benefit of being actually connected to the systems that we use to develop C-Reduce.

If you want to contribute to C-Reduce, or make a fork, you would be better off cloning the git repository!

**Comment by eeide** [comment]
Let me know if the previous comment addresses your questions. If it does, then I will close this issue. Thanks!

**Comment by maxim-belkin** [comment]
Yes, thanks for explaining! It might be good either to name them differently (suffix?) or add this note somewhere :)

**Comment by regehr** [comment]
I agree-- let's use different names.

**Comment by eeide** [comment]
OK, I will call the release tarball something else in the future. Thanks—
